name: Create Issue
description: Create a new Issue
labels: [new]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Also tell us, what did you expect to happen?
      placeholder: "Please provide a summary."
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Intended Outcome
      placeholder: "Please specify the intended outcome."
    validations:
      required: true
  - type: textarea
    id: function
    attributes:
      label: How will it work?
      placeholder: "Please explain how it will work."
    validations:
      required: true
